### Get all tags
GET http://localhost:3000/tags

### Create a tag
POST http://localhost:3000/tags
Content-Type: application/json

{
  "name": "scala",
  "slug": "scala",
  "description": "Scala programming language"
}

### Delete a tag
DELETE http://localhost:3000/tags/7
