### Get all users
GET http://localhost:3000/posts

### Create a post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My Second Post",
  "slug": "my-second-post",
  "postType": "post",
  "status": "draft",
  "content": "This is the content of my first post",
  "schema": "{\"key\": \"value\"}",
  "featuredImageUrl": "https://example.com/image.jpg",
  "publishOn": "2024-01-01T00:00:00.000Z",
  "metaOptions": {
    "metaValue": "{\"key\": \"value\"}"
  },
  "authorId": 3,
  "tagIds": [
    8
  ]
}

### Update a post
PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": 26,
  "title": "My AAA Post",
  "postType": "post",
  "status": "draft",
  "content": "test content",
  "metaOptions": {
    "metaValue": "{\"aaa\": \"bbb\"}"
  },
  "tags": [
    5
  ]
}

### Delete a post
DELETE http://localhost:3000/posts/25
