### Get all users
GET http://localhost:3000/posts?startDate=2021-01-01&endDate=2021-12-31&limit=10&page=1

### Create a post
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzM0NTAyNzQzLCJleHAiOjE3MzQ1MDYzNDMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.UNIcZkY5nPiBF_j02IsD_A8KdXCA6frK_4_1gZa7kjY

{
  "title": "My Second Post",
  "slug": "my-second-post",
  "postType": "post",
  "status": "draft",
  "content": "This is the content of my first post",
  "schema": "{\"key\": \"value\"}",
  "featuredImageUrl": "https://example.com/image.jpg",
  "metaOptions": {
    "metaValue": "{\"key\": \"value\"}"
  },
  "tagIds": [
    8
  ]
}

### Update a post
PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": 26,
  "title": "My AAA Post",
  "postType": "post",
  "status": "draft",
  "content": "test content",
  "metaOptions": {
    "metaValue": "{\"aaa\": \"bbb\"}"
  },
  "tagIds": [
    5
  ]
}

### Delete a post
DELETE http://localhost:3000/posts/25
