### Get all users
GET http://localhost:3000/posts/1234

### Create a post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My First Post",
    "slug": "my-first-post",
    "postType": "post",
    "status": "draft",
    "slug": "new-with-nestjs",
    "content": "This is the content of my first post",
    "schema": "{\"key\": \"value\"}",
    "featuredImageUrl": "https://example.com/image.jpg",
    "publishOn": "2024-01-01T00:00:00.000Z",
    "tags": ["nestjs", "typescript"],
    "metaOptions": [{"key": "sidebarEnabled", "value": true}]
}

### Update a post
PATCH http://localhost:3000/posts
Content-Type: application/json

{
    "id": 1234,
    "title": "My First Post"
}
